### ISSUE TITLE
CallExpression error "unknowncallee type: Super"

### ISSUE THREAD

**Issue by Controlix** [Gvozd/eslint-plugin-consistent-subscribe#5]
When I try to use this plugin on a TypeScript code base, in combination with @typescript-eslint plugin, I get following error:

> Error: unknown callee type: Super
Occurred while linting /home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/src/app/api/services/arbeidsregimes-controller.service.ts:25
    at CallExpression (/home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/node_modules/eslint-plugin-consistent-subscribe/lib/rules/consistent-subscribe.js:108:31)
    at /home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/MBOGAER1/projects/vindeenwerknemer/vindeenwerknemer-ui/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)

Here is my eslintrc config file:

```js
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint',
    'consistent-subscribe',
  ],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
  ],
  rules: {
    'consistent-subscribe/consistent-subscribe': 2,
  }
};
```

**Comment by Gvozd** [comment]
fixes at 1.4.0
